### ISSUE TITLE
Bluecoders.io tags are not very well imported

### ISSUE THREAD

**Issue by lebouquetin** [pyjobs/crawlers#12]
Tags are imported as-is for example "recrutement développeur docker" instead of "docker". that would be nice to adapt the crawler in order to remove the useless part of tags "recrutement développeur"

**Comment by CkuT** [comment]
Do you have more details ? I don't have this issue.
When I execute the test spider, I get the following output :

```
"tags": [
        "javascript", 
        "nodejs", 
        "reactjs", 
        "angularjs", 
        "mongodb"
    ],
```

**Comment by lebouquetin** [comment]
You're totally right, sorry
