### ISSUE TITLE
No logo for LinuxJobs

### ISSUE THREAD

**Issue by ghost** [pyjobs/crawlers#16]
Hi,

On pyjobs.fr, no logo is displayed for the offers from LinuxJobs. Checking the code it seems linking to https://pbs.twimg.com/profile_images/649599776573403140/vaMrmib1_400x400.png but it does not seem to work.

If you tell me what size you need, I can upload a logo to be used by your crawler.

Regards,
Carl Chenet

**Comment by buxx** [comment]
Hello,

Sorry for the long time response, there is the change: https://github.com/pyjobs/crawlers/commit/a1ba2f1200d7e211553a116ae59f5f41043edb7f

Thank's for report :p !

PS: If you prefer a different logo, you can upload it and we will use it as you say.
